name: mocuply
description: "Design high-resolution App Store and Google Play mockup screenshots directly in your browser. 100% free, client-side, open-source."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  file_picker: ^8.1.7
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.2
  archive: ^4.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
